### ISSUE TITLE
Unable to pass tests with range checking

### ISSUE THREAD

**Issue by pda0** [graemeg/fptest#4]
If test project compilled with range checking and at least one of test classes has more than one test method the test application is failed with unhandled range checking exception. It happends because entries[] array is defined as [0..0].

I made a patch for it (also update vmt parser to current objpas.inc implementation, tested on fpc 2.6.4 and 2.7.1): http://pastebin.com/83d3iibM
Sorry, I'm still newbie in git and github.

**Comment by graemeg** [comment]
Many thanks for the contribution. My apologies for being so very late. Your patch has been applied to "master" as commit 3cb04c24.
