### ISSUE TITLE
Directory where configuration file is stored

### ISSUE THREAD

**Issue by blikblum** [graemeg/fptest#9]
In Delphi the configuration file was stored in a shared directory. When porting to fpc this feature  was removed because used a windows function to determine the directory and the config file is now stored in the same dir as the executable.

In fpc, there's a cross  platform function to determine a shared directory (`GetAppConfigDir`) to store the configuration.

When porting the GUI Test Runner to LCL i used this function ( See `TGUITestRunner.InitializeAppDataPath`) but disabled its usage because it would get two config files. One created by the GUI Runner other by the core framework (See `TProjectManager.SaveConfiguration`)

I order to allow saving the config file in a global directory, i think of the following solution

- Create a ConfigPath var in ProjectManager (a class property?)
- By default would be empty (backward compatible)
- It could be set at app start 
- The new created projects would generate the code pointing to GetAppConfigDir (follows delphi behavior), none (current behavior) according to an option at the project descriptor (Lazarus Project template).

Discussing here before doing a PR, since it's a big change

**Comment by graemeg** [comment]
Can we continue the discussion in fptest.support please. I hate web interfaces. ;-)

As for the config file location. I purposely changed it for some reason (and purposely not used GetAppConfigDir()). I'll have to check the commit logs or code comments to see the reasoning. I can't remember off the top of my head.

**Comment by blikblum** [comment]
Closing the issue since is not a deal breaker and there are ways to avoid the extra file in diretory
